
name: Build and Deploy Backend

on:
  push:
    branches:
      - develop

jobs:
  backend-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Artifact Registry用Docker認証
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --project=${{ vars.PROJECT_ID }}

      # バックエンドイメージのビルド＆プッシュ
      - name: Build and push backend image
        run: |
          docker build -t ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO_NAME }}/${{ vars.BACKEND_IMAGE }}:latest ./backend
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO_NAME }}/${{ vars.BACKEND_IMAGE }}:latest

      # 環境変数ファイルの作成
      - name: Create env vars file
        run: |
          cat <<EOF > /tmp/backend_env.yml
          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          API_VERSION: ${{ vars.API_VERSION }}
          IS_DEPLOYED: ${{ vars.IS_DEPLOYED }}
          EOF

      # バックエンドサービスのデプロイとURL取得
      - name: Deploy backend service to Cloud Run
        id: deploy-backend
        run: |
          gcloud run deploy ${{ vars.BACKEND_IMAGE }} \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPO_NAME }}/${{ vars.BACKEND_IMAGE }}:latest \
            --port=8000 \
            --region=${{ vars.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --env-vars-file /tmp/backend_env.yml \
            --quiet